{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "argobot.fullname" . }}
  labels:
{{- include "argobot.labels" . | nindent 4 }}
data:
  config.yml: |
{{ .Values.config | indent 4 }}
{{- end -}}
