// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RepositoryPluginAppSpec PluginAppSpec contains details about a plugin-type Application
//
// swagger:model repositoryPluginAppSpec
type RepositoryPluginAppSpec struct {

	// parameters announcement
	ParametersAnnouncement []*RepositoryParameterAnnouncement `json:"parametersAnnouncement"`
}

// Validate validates this repository plugin app spec
func (m *RepositoryPluginAppSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParametersAnnouncement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RepositoryPluginAppSpec) validateParametersAnnouncement(formats strfmt.Registry) error {
	if swag.IsZero(m.ParametersAnnouncement) { // not required
		return nil
	}

	for i := 0; i < len(m.ParametersAnnouncement); i++ {
		if swag.IsZero(m.ParametersAnnouncement[i]) { // not required
			continue
		}

		if m.ParametersAnnouncement[i] != nil {
			if err := m.ParametersAnnouncement[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("parametersAnnouncement" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("parametersAnnouncement" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this repository plugin app spec based on the context it is used
func (m *RepositoryPluginAppSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParametersAnnouncement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RepositoryPluginAppSpec) contextValidateParametersAnnouncement(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ParametersAnnouncement); i++ {

		if m.ParametersAnnouncement[i] != nil {

			if swag.IsZero(m.ParametersAnnouncement[i]) { // not required
				return nil
			}

			if err := m.ParametersAnnouncement[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("parametersAnnouncement" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("parametersAnnouncement" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RepositoryPluginAppSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepositoryPluginAppSpec) UnmarshalBinary(b []byte) error {
	var res RepositoryPluginAppSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
