// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSetStrategy ApplicationSetStrategy configures how generated Applications are updated in sequence.
//
// swagger:model v1alpha1ApplicationSetStrategy
type V1alpha1ApplicationSetStrategy struct {

	// rolling sync
	RollingSync *V1alpha1ApplicationSetRolloutStrategy `json:"rollingSync,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this v1alpha1 application set strategy
func (m *V1alpha1ApplicationSetStrategy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRollingSync(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationSetStrategy) validateRollingSync(formats strfmt.Registry) error {
	if swag.IsZero(m.RollingSync) { // not required
		return nil
	}

	if m.RollingSync != nil {
		if err := m.RollingSync.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rollingSync")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rollingSync")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 application set strategy based on the context it is used
func (m *V1alpha1ApplicationSetStrategy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRollingSync(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationSetStrategy) contextValidateRollingSync(ctx context.Context, formats strfmt.Registry) error {

	if m.RollingSync != nil {

		if swag.IsZero(m.RollingSync) { // not required
			return nil
		}

		if err := m.RollingSync.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rollingSync")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rollingSync")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSetStrategy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSetStrategy) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSetStrategy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
