// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1PluginConfigMapRef v1alpha1 plugin config map ref
//
// swagger:model v1alpha1PluginConfigMapRef
type V1alpha1PluginConfigMapRef struct {

	// Name of the ConfigMap
	Name string `json:"name,omitempty"`
}

// Validate validates this v1alpha1 plugin config map ref
func (m *V1alpha1PluginConfigMapRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 plugin config map ref based on context it is used
func (m *V1alpha1PluginConfigMapRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1PluginConfigMapRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1PluginConfigMapRef) UnmarshalBinary(b []byte) error {
	var res V1alpha1PluginConfigMapRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
