// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSetRolloutStep v1alpha1 application set rollout step
//
// swagger:model v1alpha1ApplicationSetRolloutStep
type V1alpha1ApplicationSetRolloutStep struct {

	// match expressions
	MatchExpressions []*V1alpha1ApplicationMatchExpression `json:"matchExpressions"`

	// max update
	MaxUpdate *IntstrIntOrString `json:"maxUpdate,omitempty"`
}

// Validate validates this v1alpha1 application set rollout step
func (m *V1alpha1ApplicationSetRolloutStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMatchExpressions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxUpdate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationSetRolloutStep) validateMatchExpressions(formats strfmt.Registry) error {
	if swag.IsZero(m.MatchExpressions) { // not required
		return nil
	}

	for i := 0; i < len(m.MatchExpressions); i++ {
		if swag.IsZero(m.MatchExpressions[i]) { // not required
			continue
		}

		if m.MatchExpressions[i] != nil {
			if err := m.MatchExpressions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("matchExpressions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("matchExpressions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ApplicationSetRolloutStep) validateMaxUpdate(formats strfmt.Registry) error {
	if swag.IsZero(m.MaxUpdate) { // not required
		return nil
	}

	if m.MaxUpdate != nil {
		if err := m.MaxUpdate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("maxUpdate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("maxUpdate")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 application set rollout step based on the context it is used
func (m *V1alpha1ApplicationSetRolloutStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMatchExpressions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMaxUpdate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationSetRolloutStep) contextValidateMatchExpressions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MatchExpressions); i++ {

		if m.MatchExpressions[i] != nil {

			if swag.IsZero(m.MatchExpressions[i]) { // not required
				return nil
			}

			if err := m.MatchExpressions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("matchExpressions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("matchExpressions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ApplicationSetRolloutStep) contextValidateMaxUpdate(ctx context.Context, formats strfmt.Registry) error {

	if m.MaxUpdate != nil {

		if swag.IsZero(m.MaxUpdate) { // not required
			return nil
		}

		if err := m.MaxUpdate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("maxUpdate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("maxUpdate")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSetRolloutStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSetRolloutStep) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSetRolloutStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
