// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationMatchExpression v1alpha1 application match expression
//
// swagger:model v1alpha1ApplicationMatchExpression
type V1alpha1ApplicationMatchExpression struct {

	// key
	Key string `json:"key,omitempty"`

	// operator
	Operator string `json:"operator,omitempty"`

	// values
	Values []string `json:"values"`
}

// Validate validates this v1alpha1 application match expression
func (m *V1alpha1ApplicationMatchExpression) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 application match expression based on context it is used
func (m *V1alpha1ApplicationMatchExpression) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationMatchExpression) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationMatchExpression) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationMatchExpression
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
