// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1KustomizeResID v1alpha1 kustomize res Id
//
// swagger:model v1alpha1KustomizeResId
type V1alpha1KustomizeResID struct {

	// gvk
	Gvk *V1alpha1KustomizeGvk `json:"gvk,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this v1alpha1 kustomize res Id
func (m *V1alpha1KustomizeResID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGvk(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1KustomizeResID) validateGvk(formats strfmt.Registry) error {
	if swag.IsZero(m.Gvk) { // not required
		return nil
	}

	if m.Gvk != nil {
		if err := m.Gvk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gvk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gvk")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 kustomize res Id based on the context it is used
func (m *V1alpha1KustomizeResID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGvk(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1KustomizeResID) contextValidateGvk(ctx context.Context, formats strfmt.Registry) error {

	if m.Gvk != nil {

		if swag.IsZero(m.Gvk) { // not required
			return nil
		}

		if err := m.Gvk.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gvk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gvk")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1KustomizeResID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1KustomizeResID) UnmarshalBinary(b []byte) error {
	var res V1alpha1KustomizeResID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
