// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSetApplicationStatus ApplicationSetApplicationStatus contains details about each Application managed by the ApplicationSet
//
// swagger:model v1alpha1ApplicationSetApplicationStatus
type V1alpha1ApplicationSetApplicationStatus struct {

	// Application contains the name of the Application resource
	Application string `json:"application,omitempty"`

	// last transition time
	// Format: date-time
	LastTransitionTime V1Time `json:"lastTransitionTime,omitempty"`

	// Message contains human-readable message indicating details about the status
	Message string `json:"message,omitempty"`

	// Status contains the AppSet's perceived status of the managed Application resource: (Waiting, Pending, Progressing, Healthy)
	Status string `json:"status,omitempty"`

	// Step tracks which step this Application should be updated in
	Step string `json:"step,omitempty"`

	// TargetRevision tracks the desired revisions the Application should be synced to.
	Targetrevisions []string `json:"targetrevisions"`
}

// Validate validates this v1alpha1 application set application status
func (m *V1alpha1ApplicationSetApplicationStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastTransitionTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationSetApplicationStatus) validateLastTransitionTime(formats strfmt.Registry) error {
	if swag.IsZero(m.LastTransitionTime) { // not required
		return nil
	}

	if err := m.LastTransitionTime.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("lastTransitionTime")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("lastTransitionTime")
		}
		return err
	}

	return nil
}

// ContextValidate validate this v1alpha1 application set application status based on the context it is used
func (m *V1alpha1ApplicationSetApplicationStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLastTransitionTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationSetApplicationStatus) contextValidateLastTransitionTime(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.LastTransitionTime) { // not required
		return nil
	}

	if err := m.LastTransitionTime.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("lastTransitionTime")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("lastTransitionTime")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSetApplicationStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSetApplicationStatus) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSetApplicationStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
