// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1KustomizeSelector v1alpha1 kustomize selector
//
// swagger:model v1alpha1KustomizeSelector
type V1alpha1KustomizeSelector struct {

	// annotation selector
	AnnotationSelector string `json:"annotationSelector,omitempty"`

	// label selector
	LabelSelector string `json:"labelSelector,omitempty"`

	// res Id
	ResID *V1alpha1KustomizeResID `json:"resId,omitempty"`
}

// Validate validates this v1alpha1 kustomize selector
func (m *V1alpha1KustomizeSelector) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1KustomizeSelector) validateResID(formats strfmt.Registry) error {
	if swag.IsZero(m.ResID) { // not required
		return nil
	}

	if m.ResID != nil {
		if err := m.ResID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resId")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resId")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 kustomize selector based on the context it is used
func (m *V1alpha1KustomizeSelector) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1KustomizeSelector) contextValidateResID(ctx context.Context, formats strfmt.Registry) error {

	if m.ResID != nil {

		if swag.IsZero(m.ResID) { // not required
			return nil
		}

		if err := m.ResID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resId")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resId")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1KustomizeSelector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1KustomizeSelector) UnmarshalBinary(b []byte) error {
	var res V1alpha1KustomizeSelector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
