// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1RevisionHistory RevisionHistory contains history information about a previous sync
//
// swagger:model v1alpha1RevisionHistory
type V1alpha1RevisionHistory struct {

	// deploy started at
	// Format: date-time
	DeployStartedAt V1Time `json:"deployStartedAt,omitempty"`

	// deployed at
	// Format: date-time
	DeployedAt V1Time `json:"deployedAt,omitempty"`

	// ID is an auto incrementing identifier of the RevisionHistory
	ID int64 `json:"id,omitempty"`

	// initiated by
	InitiatedBy *V1alpha1OperationInitiator `json:"initiatedBy,omitempty"`

	// Revision holds the revision the sync was performed against
	Revision string `json:"revision,omitempty"`

	// Revisions holds the revision of each source in sources field the sync was performed against
	Revisions []string `json:"revisions"`

	// source
	Source *V1alpha1ApplicationSource `json:"source,omitempty"`

	// Sources is a reference to the application sources used for the sync operation
	Sources []*V1alpha1ApplicationSource `json:"sources"`
}

// Validate validates this v1alpha1 revision history
func (m *V1alpha1RevisionHistory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeployStartedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeployedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInitiatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1RevisionHistory) validateDeployStartedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.DeployStartedAt) { // not required
		return nil
	}

	if err := m.DeployStartedAt.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("deployStartedAt")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("deployStartedAt")
		}
		return err
	}

	return nil
}

func (m *V1alpha1RevisionHistory) validateDeployedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.DeployedAt) { // not required
		return nil
	}

	if err := m.DeployedAt.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("deployedAt")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("deployedAt")
		}
		return err
	}

	return nil
}

func (m *V1alpha1RevisionHistory) validateInitiatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.InitiatedBy) { // not required
		return nil
	}

	if m.InitiatedBy != nil {
		if err := m.InitiatedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("initiatedBy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("initiatedBy")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1RevisionHistory) validateSource(formats strfmt.Registry) error {
	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1RevisionHistory) validateSources(formats strfmt.Registry) error {
	if swag.IsZero(m.Sources) { // not required
		return nil
	}

	for i := 0; i < len(m.Sources); i++ {
		if swag.IsZero(m.Sources[i]) { // not required
			continue
		}

		if m.Sources[i] != nil {
			if err := m.Sources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sources" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1alpha1 revision history based on the context it is used
func (m *V1alpha1RevisionHistory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeployStartedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDeployedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInitiatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1RevisionHistory) contextValidateDeployStartedAt(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.DeployStartedAt) { // not required
		return nil
	}

	if err := m.DeployStartedAt.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("deployStartedAt")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("deployStartedAt")
		}
		return err
	}

	return nil
}

func (m *V1alpha1RevisionHistory) contextValidateDeployedAt(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.DeployedAt) { // not required
		return nil
	}

	if err := m.DeployedAt.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("deployedAt")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("deployedAt")
		}
		return err
	}

	return nil
}

func (m *V1alpha1RevisionHistory) contextValidateInitiatedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.InitiatedBy != nil {

		if swag.IsZero(m.InitiatedBy) { // not required
			return nil
		}

		if err := m.InitiatedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("initiatedBy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("initiatedBy")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1RevisionHistory) contextValidateSource(ctx context.Context, formats strfmt.Registry) error {

	if m.Source != nil {

		if swag.IsZero(m.Source) { // not required
			return nil
		}

		if err := m.Source.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1RevisionHistory) contextValidateSources(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sources); i++ {

		if m.Sources[i] != nil {

			if swag.IsZero(m.Sources[i]) { // not required
				return nil
			}

			if err := m.Sources[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sources" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1RevisionHistory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1RevisionHistory) UnmarshalBinary(b []byte) error {
	var res V1alpha1RevisionHistory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
