// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1KustomizeGvk v1alpha1 kustomize gvk
//
// swagger:model v1alpha1KustomizeGvk
type V1alpha1KustomizeGvk struct {

	// group
	Group string `json:"group,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this v1alpha1 kustomize gvk
func (m *V1alpha1KustomizeGvk) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 kustomize gvk based on context it is used
func (m *V1alpha1KustomizeGvk) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1KustomizeGvk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1KustomizeGvk) UnmarshalBinary(b []byte) error {
	var res V1alpha1KustomizeGvk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
