// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ChartDetails ChartDetails contains helm chart metadata for a specific version
//
// swagger:model v1alpha1ChartDetails
type V1alpha1ChartDetails struct {

	// description
	Description string `json:"description,omitempty"`

	// The URL of this projects home page, e.g. "http://example.com"
	Home string `json:"home,omitempty"`

	// List of maintainer details, name and email, e.g. ["John Doe <john_doe@my-company.com>"]
	Maintainers []string `json:"maintainers"`
}

// Validate validates this v1alpha1 chart details
func (m *V1alpha1ChartDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 chart details based on context it is used
func (m *V1alpha1ChartDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ChartDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ChartDetails) UnmarshalBinary(b []byte) error {
	var res V1alpha1ChartDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
