// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationPreservedFields v1alpha1 application preserved fields
//
// swagger:model v1alpha1ApplicationPreservedFields
type V1alpha1ApplicationPreservedFields struct {

	// annotations
	Annotations []string `json:"annotations"`

	// labels
	Labels []string `json:"labels"`
}

// Validate validates this v1alpha1 application preserved fields
func (m *V1alpha1ApplicationPreservedFields) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 application preserved fields based on context it is used
func (m *V1alpha1ApplicationPreservedFields) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationPreservedFields) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationPreservedFields) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationPreservedFields
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
