// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1TagFilter v1alpha1 tag filter
//
// swagger:model v1alpha1TagFilter
type V1alpha1TagFilter struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this v1alpha1 tag filter
func (m *V1alpha1TagFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 tag filter based on context it is used
func (m *V1alpha1TagFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1TagFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1TagFilter) UnmarshalBinary(b []byte) error {
	var res V1alpha1TagFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
