// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ManagedNamespaceMetadata v1alpha1 managed namespace metadata
//
// swagger:model v1alpha1ManagedNamespaceMetadata
type V1alpha1ManagedNamespaceMetadata struct {

	// annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`
}

// Validate validates this v1alpha1 managed namespace metadata
func (m *V1alpha1ManagedNamespaceMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 managed namespace metadata based on context it is used
func (m *V1alpha1ManagedNamespaceMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ManagedNamespaceMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ManagedNamespaceMetadata) UnmarshalBinary(b []byte) error {
	var res V1alpha1ManagedNamespaceMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
