// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSourcePluginParameter v1alpha1 application source plugin parameter
//
// swagger:model v1alpha1ApplicationSourcePluginParameter
type V1alpha1ApplicationSourcePluginParameter struct {

	// Array is the value of an array type parameter.
	Array []string `json:"array"`

	// Map is the value of a map type parameter.
	Map map[string]string `json:"map,omitempty"`

	// Name is the name identifying a parameter.
	Name string `json:"name,omitempty"`

	// String_ is the value of a string type parameter.
	String string `json:"string,omitempty"`
}

// Validate validates this v1alpha1 application source plugin parameter
func (m *V1alpha1ApplicationSourcePluginParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 application source plugin parameter based on context it is used
func (m *V1alpha1ApplicationSourcePluginParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSourcePluginParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSourcePluginParameter) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSourcePluginParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
