// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSetResourceIgnoreDifferences ApplicationSetResourceIgnoreDifferences configures how the ApplicationSet controller will ignore differences in live
// applications when applying changes from generated applications.
//
// swagger:model v1alpha1ApplicationSetResourceIgnoreDifferences
type V1alpha1ApplicationSetResourceIgnoreDifferences struct {

	// JQPathExpressions is a list of JQ path expressions to fields to ignore differences for.
	JqPathExpressions []string `json:"jqPathExpressions"`

	// JSONPointers is a list of JSON pointers to fields to ignore differences for.
	JSONPointers []string `json:"jsonPointers"`

	// Name is the name of the application to ignore differences for. If not specified, the rule applies to all applications.
	Name string `json:"name,omitempty"`
}

// Validate validates this v1alpha1 application set resource ignore differences
func (m *V1alpha1ApplicationSetResourceIgnoreDifferences) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 application set resource ignore differences based on context it is used
func (m *V1alpha1ApplicationSetResourceIgnoreDifferences) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSetResourceIgnoreDifferences) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSetResourceIgnoreDifferences) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSetResourceIgnoreDifferences
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
