apps:
  create: true

argo-cd:

  global:
    domain: localhost
    
  # server:
  #   ingress:
  #     enabled: true
  #     annotations:
  #       kubernetes.io/ingress.class: "nginx"
  #       nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  #       nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #     hosts:
  #       - argocd.local

  configs:
    cm:
      admin.enabled: true
      accounts.admin: apiKey, login
      accounts.developer: apiKey
    rbac:
      policy.csv: |
        p, developer, applications, get, */*, allow
        p, developer, applications, create, */*, allow
        p, developer, applications, sync, */*, allow
        p, developer, applications, update, */*, allow
    params:
      server.insecure: true
      server.disable.auth: false
