argo-cd:

  global:
    domain: localhost
    
  # server:
  #   ingress:
  #     enabled: true
  #     annotations:
  #       kubernetes.io/ingress.class: "nginx"
  #       nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  #       nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #     hosts:
  #       - argocd.local

  configs:
    cm:
      admin.enabled: true
      accounts.admin: apiKey, login
    params:
      server.insecure: true
      server.disable.auth: false
