name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.8"
      - uses: helm/kind-action@v1
      - run: |
          go mod download
          go test ./test/integration/
