name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - run: helm dependency update ./charts/argocd
      - run: go mod download
      - run: go test ./pkg/...
      - run: go test ./test/integration/ --create-crds "true"
